---
- name: Run converge
  import_playbook: "../shared/converge.yml"
  vars:
    env_files:
      - "{{ playbook_dir }}/../../.env.testing"
      - "{{ playbook_dir }}/../../../rewardsweb/.env.testing"
      - "{{ playbook_dir }}/../../../rewardsweb/rewardsbot/.env"
