---
- name: Load .env.testing for Molecule
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load environment variables from .env.testing
      set_fact:
        env_vars: "{{ env_vars | default({}) | combine({item.split('=')[0]: item.split('=')[1]}) }}"
      loop: "{{ lookup('file', '../../.env.testing').splitlines() }}"
      when: item is search('=')

- name: Converge Testing Environment
  hosts: all
  gather_facts: true
  vars_files:
    - ../../group_vars/testing/vars.yml
  roles:
    - createuser
    - gunicorn
