---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu2404
    image: trfore/docker-ubuntu2404-systemd:latest
    privileged: true        # required for systemd boot
    command: "/sbin/init"   # required for systemd boot
    pre_build_image: true

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_COLLECTIONS_PATHS: "../../collections"
  inventory:
    host_vars:
      ubuntu2404:
        ansible_connection: docker
        ansible_user: root

verifier:
  name: ansible
