---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: testing-instance
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    ansible.builtin.command: /sbin/init
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_COLLECTIONS_PATHS: "../../collections"
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      testing-instance:
        ansible_connection: docker

verifier:
  name: ansible
