---
- name: Verify testing environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify Gunicorn service file exists
      ansible.builtin.stat:
        path: /etc/systemd/system/gunicorn.service
      register: gunicorn_file

    - name: Ensure Gunicorn systemd unit file present
      ansible.builtin.assert:
        that:
          - gunicorn_file.stat.exists
        fail_msg: "Gunicorn service file not found!"
        success_msg: "Gunicorn service file found ✅"
