---
- name: Import SSH hardening tasks
  ansible.builtin.import_tasks: ssh.yml
  when: not is_molecule_test | default(false)

- name: Import kernel hardening tasks
  ansible.builtin.import_tasks: kernel.yml

- name: Import CIS removal tasks
  ansible.builtin.import_tasks: cis_remove.yml

- name: Import Fail2Ban configuration tasks
  ansible.builtin.import_tasks: fail2ban.yml

- name: Import audit tasks
  ansible.builtin.import_tasks: audit.yml
