---
- name: "Ensure opt/archives directory exists for {{ admin_user }}"
  ansible.builtin.file:
    path: "{{ opt_folder }}archives"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
    mode: "0755"
  become: true
  become_user: "{{ admin_user }}"
  tags: [audit, lynis]

- name: Get username running the playbook
  ansible.builtin.command: whoami
  delegate_to: localhost
  delegate_facts: false
  run_once: true
  register: hardening_host_username_lynis
  changed_when: false
  vars:
    ansible_connection: local
  tags: [audit, lynis]

- name: Copy Lynis archive from local host
  ansible.builtin.copy:
    src: "/home/{{ hardening_host_username_lynis.stdout_lines[0] }}/opt/archives/lynis-{{ lynis_version }}.tar.gz"
    dest: "{{ opt_folder }}archives/lynis-{{ lynis_version }}.tar.gz"
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
    mode: "0640"
  become: true
  notify: Lynis downloaded
  tags: [audit, lynis]

- name: Deploy Lynis cron job script
  ansible.builtin.template:
    src: lyniscron.sh
    dest: "{{ opt_folder }}lyniscron.sh"
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
    mode: "0755"
  tags: [audit, lynis]

- name: Create weekly Lynis cron job
  ansible.builtin.cron:
    name: "lynis-weekly"
    day: "4"
    hour: "5"
    minute: "20"
    user: root
    job: ": Lynis weekly ; {{ opt_folder }}lyniscron.sh"
  become: true
  tags: [audit, lynis, cronjobs]
