---
- name: Deploy custom /etc/motd
  ansible.builtin.template:
    src: motd.txt
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: [audit, audit-motd]

- name: Remove default MOTD help text
  ansible.builtin.lineinfile:
    path: /etc/update-motd.d/10-help-text
    state: absent
    regexp: "{{ item }}"
  become: true
  loop:
    - 'Documentation:'
    - 'Management:'
    - 'Support:'
  tags: [audit, audit-motd]

- name: Disable MOTD news feature
  ansible.builtin.lineinfile:
    path: /etc/default/motd-news
    regexp: "^ENABLED="
    line: "ENABLED=0"
    state: present
  become: true
  when: not is_molecule_test | default(false)
  tags: [audit, audit-motd]
