---
- name: Ensure 127.0.0.1 entry for localhost and project
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1   {{ project_name }}   localhost"
    state: present
  become: true
  when: not is_molecule_test | default(false)
  tags: [hosts]

- name: Ensure 127.0.1.1 entry for hostname and project
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1   {{ project_name }}   {{ ansible_hostname }}"
    state: present
  become: true
  when: not is_molecule_test | default(false)
  tags: [hosts]

- name: Ensure inventory host entry appears after 127.0.1.1
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{ inventory_hostname }}'
    insertafter: '^127\.0\.1\.1'
    line: "{{ inventory_hostname }}   {{ project_name }}   {{ ansible_hostname }}"
    state: present
  become: true
  when: not is_molecule_test | default(false)
  tags: [hosts]
