---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  changed_when: false
  tags: [prepare-host, uptodate]

- name: Ensure setfacl tool (ACL management) is installed
  ansible.builtin.apt:
    name: acl
    state: present
  become: true
  tags: [prepare-host, setfacl]

- name: Ensure required Python 3 packages are installed
  ansible.builtin.apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
    state: present
  become: true
  tags: [prepare-host, python3-install]

- name: Ensure Git is installed
  ansible.builtin.apt:
    name: git
    state: present
  become: true
  tags: [repository]

- name: Ensure {{ admin_user }} opt folder exists
  ansible.builtin.file:
    path: "{{ opt_folder }}"
    state: directory
    mode: '0755'
  become: true
  tags: [audit, lynis]
