---
- name: Restart postgresql
  become: true
  ansible.builtin.systemd:
    name: postgresql
    state: restarted

- name: Restart pgbouncer
  become: true
  ansible.builtin.systemd:
    name: pgbouncer
    state: restarted
