---
- name: Tune PostgreSQL for webserver
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp: "{{ item.regex }}"
    line: "{{ item.value }}"
    backrefs: yes
    state: present
  become: true
  notify: Restart postgresql
  loop:
    - regex: "^#listen_addresses = 'localhost'"
      value: "listen_addresses = 'localhost,{{ hostvars['localhost'].env_vars.WEB_IP }}'"
  tags: [postgresql, postgresql-access, postgresql-allow-webserver-ip]

- name: Set access rule in pg_hba.conf for webserver
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    regexp: "{{ item.regex }}"
    line: "{{ item.value }}"
    state: present
  become: true
  notify: Restart postgresql
  loop:
    - regex: "host\\s+{{ hostvars['localhost'].env_vars.DATABASE_NAME }}\\s+{{ hostvars['localhost'].env_vars.DATABASE_USER }}\\s+{{ hostvars['localhost'].env_vars.WEB_IP }}/32.*trust"
      value: "host    {{ hostvars['localhost'].env_vars.DATABASE_NAME }}             {{ hostvars['localhost'].env_vars.DATABASE_USER }}        {{ hostvars['localhost'].env_vars.WEB_IP }}/32        trust"
  tags: [postgresql, postgresql-access, postgresql-allow-webserver-ip]

- name: Configure UFW rule for PostgreSQL
  community.general.ufw:
    rule: allow
    to_port: 5432
    proto: any
    from_ip: "{{ hostvars['localhost'].env_vars.WEB_IP }}"
    state: enabled
    comment: "Added for webserver by Ansible"
  become: true
  tags: [postgresql, postgresql-access, postgresql-allow-webserver-ip]
