---
- name: Check if {{ database_backup_folder }} folder exists
  file:
    path: "{{ database_backup_folder }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: 0755
  tags: [postgresql, postgresql-install, postgresql-backup-config]

- name: Copy pg_backup configuration file to backups folder
  template:
    src: pg_backup.config
    dest: "{{ database_backup_folder }}pg_backup.config"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: 0644
  tags: [postgresql, postgresql-install, postgresql-backup-config]

- name: Copy pg_backup_rotated script to backups folder
  template:
    src: pg_backup_rotated.sh
    dest: "{{ database_backup_folder }}pg_backup_rotated.sh"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: 0755
  tags: [postgresql, postgresql-install, postgresql-backup-config]

- name: Create hourly database backup cronjob
  cron:
    hour: "*"
    minute: "30"
    name: "{{ project_name }} database backup (hourly schedule)"
    user: "{{ admin_user }}"
    job: ": Database hourly backup ; {{ database_backup_folder }}pg_backup_rotated.sh"
  become: true
  tags: [postgresql, postgresql-install, postgresql-backup-config, cronjobs]

