---
- name: Apply PostgreSQL environment when testing under Molecule
  ansible.builtin.set_fact:
    postgresql_pg_env: "{{ pg_env | default({}) }}"

- name: Create postgresql user
  community.postgresql.postgresql_user:
    name: "{{ hostvars['localhost'].env_vars.DATABASE_USER }}"
    password: "{{ hostvars['localhost'].env_vars.DATABASE_PASSWORD }}"
    role_attr_flags: "CREATEDB,NOSUPERUSER"
    state: present
    encrypted: true
  become: true
  become_user: postgres
  environment: "{{ postgresql_pg_env | default({}) }}"
  tags: [postgresql, postgresql-create]

- name: Create postgresql database
  community.postgresql.postgresql_db:
    name: "{{ hostvars['localhost'].env_vars.DATABASE_NAME }}"
    owner: "{{ hostvars['localhost'].env_vars.DATABASE_USER }}"
    encoding: 'UTF-8'
    state: present
  register: postgresql_database_created
  become: true
  become_user: postgres
  environment: "{{ postgresql_pg_env | default({}) }}"
  tags: [postgresql, postgresql-create]

- name: Ensure pg_trgm extension is enabled
  community.postgresql.postgresql_ext:
    name: pg_trgm
    login_db: "{{ hostvars['localhost'].env_vars.DATABASE_NAME }}"
    state: present
  become: true
  become_user: postgres
  environment: "{{ postgresql_pg_env | default({}) }}"
  tags: [postgresql, postgresql-create]
