---
- name: Make sure postgresql packages are installed
  ansible.builtin.apt:
    name:
      - libpq-dev
      - postgresql
      - postgresql-contrib
      - python3-psycopg
    state: present
  become: true
  tags: [postgresql, postgresql-install]

- name: Copy pg_service configuration file
  ansible.builtin.template:
    src: pg_service.conf
    dest: "{{ site_path }}/.pg_service.conf"
    owner: "{{ webapp_user }}"
    group: "{{ webapp_group }}"
    mode: "0600"
  become: true
  tags: [postgresql, postgresql-install]

- name: Copy pgpass configuration file
  ansible.builtin.template:
    src: pgpass.conf
    dest: "{{ site_path }}/.pgpass"
    owner: "{{ webapp_user }}"
    group: "{{ webapp_group }}"
    mode: "0600"
  become: true
  tags: [postgresql, postgresql-install]

- name: Ensure PostgreSQL service is running and enabled
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
  become: true
  tags: [postgresql, postgresql-install]
