---
- name: Make sure pgbouncer package is installed
  ansible.builtin.apt:
    name:
      - pgbouncer
    state: present
  become: true
  tags: [postgresql, pgbouncer]

- name: Set pgbouncer users
  ansible.builtin.lineinfile:
    path: /etc/pgbouncer/userlist.txt
    line: '"{{ global_env_vars["DATABASE_NAME"] }}" "{{ global_env_vars["DATABASE_PASSWORD"] }}"'
    state: present
  become: true
  tags: [postgresql, pgbouncer]

- name: Tune pgbouncer
  ansible.builtin.lineinfile:
    path: /etc/pgbouncer/pgbouncer.ini
    regexp: "{{ item.regex }}"
    line: "{{ item.value }}"
    backrefs: true
    state: present
  become: true
  loop:
    - regex: "^(;)?foodb ="
      value: >-
        {{ global_env_vars['DATABASE_NAME'] }}
        = host=localhost port=5432
        dbname={{ global_env_vars['DATABASE_NAME'] }}
        user={{ global_env_vars['DATABASE_USER'] }}
        password={{ global_env_vars['DATABASE_PASSWORD'] }}

    - regex: "^(;)?admin_users = user2, someadmin, otheradmin"
      value: >-
        admin_users = postgres, {{ global_env_vars['ADMIN_USER'] }}

    - regex: "^(;)?stats_users = stats, root"
      value: >-
        stats_users = {{ global_env_vars['WEBAPP_USER'] }}, root
  notify: Restart pgbouncer
  tags: [postgresql, pgbouncer]
