---
- name: Check if we already have a certificate
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ site_name }}/fullchain.pem"
  become: true
  register: nginx_cert_stat
  tags: [nginx, letsencrypt]

- name: Set variable indicating whether we need certificate creation
  ansible.builtin.set_fact:
    nginx_need_certs: >-
      {{
        not moleculetest | default(false)
        and inventory_hostname in groups['production']
        and not nginx_cert_stat.stat.exists
      }}
  tags: [nginx, letsencrypt]

- name: "Add httponly config to nginx sites-available for {{ site_name }}"
  ansible.builtin.template:
    src: nginx.httponly.conf
    dest: "/etc/nginx/sites-available/{{ site_name }}"
    owner: root
    group: root
    mode: '0640'
    force: false
  become: true
  when: nginx_need_certs
  tags: [nginx, letsencrypt]

- name: "Add http-only config to nginx sites-available for {{ site_name }}"
  ansible.builtin.template:
    src: nginx.http-only.conf
    dest: "/etc/nginx/sites-available/{{ site_name }}"
    owner: root
    group: root
    mode: '0640'
  become: true
  when: moleculetest | default(false) or inventory_hostname in groups['testing']
  tags: [nginx, letsencrypt]

- name: "Add symlink to nginx sites-enabled for {{ site_name }}"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ site_name }}"
    dest: "/etc/nginx/sites-enabled/{{ site_name }}"
    state: link
    owner: root
    group: root
    mode: '0640'
  become: true
  when: nginx_need_certs or
        moleculetest | default(false) or
        inventory_hostname in groups['testing']
  notify: Restart nginx
  tags: [nginx, letsencrypt]

- name: Generate Let's Encrypt certificate
  ansible.builtin.command: >
    certbot certonly --non-interactive --agree-tos --no-eff-email
    --email {{ admin_email }}
    -a webroot --webroot-path /var/www/letsencrypt
    -d {{ site_name }}
  become: true
  when:
    - nginx_need_certs
    - test is not defined
  changed_when: false
  tags: [nginx, letsencrypt]

- name: "Remove httponly config from sites-enabled for {{ site_name }}"
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/{{ site_name }}"
    state: absent
  become: true
  when: nginx_need_certs
  notify: Restart nginx
  tags: [nginx, letsencrypt]

- name: "Remove httponly config from sites-available for {{ site_name }}"
  ansible.builtin.file:
    path: "/etc/nginx/sites-available/{{ site_name }}"
    state: absent
  become: true
  when: nginx_need_certs
  notify: Restart nginx
  tags: [nginx, letsencrypt]

- name: "Add ssl config to nginx sites-available for {{ site_name }}"
  ansible.builtin.template:
    src: nginx.ssl.conf
    dest: "/etc/nginx/sites-available/{{ site_name }}"
    owner: root
    group: root
    mode: '0640'
  become: true
  when: not moleculetest | default(false) and inventory_hostname in groups['production']
  tags: [nginx, nginx-snippets, letsencrypt]

- name: "Add symlink to nginx sites-enabled (SSL) for {{ site_name }}"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ site_name }}"
    dest: "/etc/nginx/sites-enabled/{{ site_name }}"
    state: link
    owner: root
    group: root
    mode: '0640'
  become: true
  notify: Restart nginx
  tags: [nginx, letsencrypt]
