---
- name: Copy letsencrypt cron file
  ansible.builtin.copy:
    src: cron_letsencrypt.sh
    dest: /var/www/cron_letsencrypt.sh
    owner: root
    group: root
    mode: "0750"
  become: true
  tags: [nginx, letsencrypt]

- name: Create Let's Encrypt renewal cron job
  ansible.builtin.cron:
    name: "Let's Encrypt certificate renewal"
    minute: "22"
    hour: "5"
    user: root
    job: ": certbot renew daily ; /usr/bin/certbot renew --quiet --noninteractive --renew-hook /var/www/cron_letsencrypt.sh"
  become: true
  when: not is_molecule_test | default(false) and inventory_hostname in groups['production']
  tags: [nginx, letsencrypt, cronjobs]
