---
- name: Setup user in nginx.conf
  replace:
    dest: /etc/nginx/nginx.conf
    regexp: "user www-data;"
    replace: "user {{ webapp_user }} {{ webapp_group }};"
  become: true
  tags: [nginx-conf]

- name: Setup use epoll main context directives
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "use epoll"
    insertafter: "^events {"
    line: "        use epoll;"
    state: present
  become: true
  tags: [nginx-conf]

- name: Setup worker_connections main context directives
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "worker_connections "
    insertafter: "^        use epoll;"
    line: "        worker_connections 1024;"
    state: present
  become: true
  tags: [nginx-conf]

- name: Setup multi_accept on main context directives
  replace:
    dest: /etc/nginx/nginx.conf
    regexp: "# multi_accept on;"
    replace: "multi_accept on;"
  become: true
  tags: [nginx-conf]

- name: Ensure gzip_disable msie6
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: 'gzip_disable "msie6";'
    insertbefore: "# gzip_vary on;"
    line: '        gzip_disable "msie6";'
    state: present
  become: true
  tags: [nginx-conf]

- name: Ensure gzip http context directive
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "gzip on;"
    insertbefore: '^        gzip_disable "msie6";'
    line: "        gzip on;"
    state: present
  become: true
  tags: [nginx-conf]

- name: Hide nginx version number from headers
  replace:
    dest: /etc/nginx/nginx.conf
    regexp: "# server_tokens off;"
    replace: "server_tokens off;"
  become: true
  tags: [nginx-conf]

- name: Add woff2 to nginx mime.types
  lineinfile:
    path: /etc/nginx/mime.types
    regexp: "font/woff2 "
    insertafter: "^    application/font-woff                 woff;"
    line: "    font/woff2                                       woff2;"
    state: present
  become: true
  tags: [nginx-conf]

- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
  become: true
  tags: [nginx-conf]
