# Generated by Django 5.1.7 on 2025-03-22 11:48

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(blank=True, max_length=58)),
                ("reddit", models.CharField(blank=True, max_length=50)),
                ("github", models.CharField(blank=True, max_length=50)),
                ("twitter", models.CharField(blank=True, max_length=50)),
                ("discord", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("name"),
                        django.db.models.functions.text.Lower("name"),
                        name="unique_contributor_name",
                    ),
                    models.UniqueConstraint(
                        models.F("address"), name="unique_contributor_address"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=20)),
                ("url", models.CharField(blank=True, max_length=255)),
                ("type", models.CharField(blank=True, max_length=20)),
                ("level", models.IntegerField(default=1)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "reward",
                    models.DecimalField(decimal_places=3, default=100, max_digits=10),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("confirmed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contributor",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cycle",
                    ),
                ),
            ],
            options={
                "ordering": ["cycle", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LegacyContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=20)),
                ("url", models.CharField(blank=True, max_length=255)),
                ("type", models.CharField(blank=True, max_length=20)),
                ("level", models.IntegerField(default=1)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "reward",
                    models.DecimalField(decimal_places=3, default=100, max_digits=10),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("confirmed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contributor",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cycle",
                    ),
                ),
            ],
            options={
                "ordering": ["cycle"],
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=20)),
                ("level", models.IntegerField(default=1)),
                (
                    "reward",
                    models.DecimalField(decimal_places=3, default=100, max_digits=10),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("general_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["type", "level"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("type", "level"), name="unique_reward_type_level"
                    )
                ],
            },
        ),
    ]
