# Generated by Django 5.2.7 on 2025-10-03 19:42

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="discord",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="github",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="reddit",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="twitter",
        ),
        migrations.CreateModel(
            name="SocialProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("prefix", models.CharField(blank=True, max_length=2)),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("name"),
                        django.db.models.functions.text.Lower("name"),
                        name="unique_socialprovider_name",
                    ),
                    models.UniqueConstraint(
                        models.F("prefix"), name="unique_socialprovider_prefix"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Handle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contributor",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.socialprovider",
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("handle")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "handle"), name="unique_social_handle"
                    )
                ],
            },
        ),
    ]
