# Generated by Django 5.2.7 on 2025-10-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_contributor_discord_remove_contributor_github_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="address",
            field=models.CharField(max_length=58, null=True),
        ),
    ]
