all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    testing:
      hosts:
        webserver_testing:
          ansible_host: 192.168.1.99

    production:
      hosts:
        webserver_production:
          ansible_host: 192.168.1.98

    ci:
      hosts:
        webserver_ci:
          ansible_host: 192.168.1.97
