---
- name: Load environment variables
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  tags: always
  tasks:
    - name: Include shared environment loader
      ansible.builtin.import_tasks: load_env.yml

- name: Check if admin_user can connect
  hosts: all
  gather_facts: false
  vars:
    ansible_user: "{{ admin_user }}"
  tasks:
    - name: Try connecting as admin_user
      ansible.builtin.ping:
      register: admin_user_ping
      ignore_unreachable: true
      ignore_errors: true
      changed_when: false

    - name: Set fallback user if admin_user unreachable
      ansible.builtin.set_fact:
        ansible_user: "{{ superuser | default('root') }}"
      when: admin_user_ping.unreachable is defined

- name: Create admin_user if missing
  hosts: all
  remote_user: "{{ superuser | default('root') }}"
  tasks:
    - name: Include createuser role
      ansible.builtin.include_role:
        name: createuser
      when: admin_user_ping.unreachable is defined

- name: Provisioning of rewardsweb project
  hosts: all
  remote_user: "{{ admin_user }}"
  roles:
    - role: setuphost
    - role: projectsetup
    - role: redis
    - role: postgresql
    - role: gunicorn
    - role: nginx
    - role: hardening
