---
- name: Load environment variables for Molecule
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  tasks:
    - name: Include shared env loader
      ansible.builtin.include_tasks: "../../load_env.yml"

- name: Converge CI environment
  hosts: all
  gather_facts: true
  vars_files:
    - ../../group_vars/ci/vars.yml
  roles:
    - setuphost
    - redis
    - postgresql
    - projectsetup
    - gunicorn
    - nginx
    - hardening
