---
- name: Run converge
  import_playbook: "../shared/converge.yml"
  vars:
    env_files:
      - "{{ playbook_dir }}/../../.env-example"
      - "{{ playbook_dir }}/../../../rewardsweb/.env-example"
      - "{{ playbook_dir }}/../../../rewardsweb/rewardsbot/.env-example"
