---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: Ci-instance
    image: ubuntu:22.04
    command: /sbin/init
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      ci-instance:
        ansible_connection: docker

verifier:
  name: ansible
