---
dependency:
  name: galaxy

driver:
  name: docker
  options:
    managed: true

platforms:
  - name: ci-instance
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    ansible.builtin.command: /sbin/init
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_COLLECTIONS_PATHS: "../../collections"
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      ci-instance:
        ansible_connection: docker

  config_options:
    defaults:
      roles_path: ../../roles

verifier:
  name: ansible
