---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu2404
    image: trfore/docker-ubuntu2404-systemd:latest
    privileged: true        # required for systemd boot
    command: "/sbin/init"   # required for systemd boot
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/tmp:/tmp"
      # - "/tmp/.ansible:/tmp/.ansible:rw"
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  pre_tasks:
    - name: Ensure /tmp/.ansible/tmp exists
      file:
        path: /tmp/.ansible/tmp
        state: directory
        mode: "0777"

  config_file: ../../ansible.cfg
  log: true
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_COLLECTIONS_PATHS: "../../collections"
    ANSIBLE_REMOTE_TEMP: "/tmp/.ansible/tmp"      # <— FORCE remote tmp
    ANSIBLE_LOCAL_TEMP: "/tmp/.ansible/local"     # (optional but avoids HOME issues)

  inventory:
    host_vars:
      ubuntu2404:
        ansible_connection: docker
        ansible_user: root

verifier:
  name: ansible
