dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu2404
    image: trfore/docker-ubuntu2404-systemd:latest
    privileged: true
    command: "/lib/systemd/systemd"
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/tmp
    pre_build_image: true

provisioner:
  name: ansible
  config_file: ../../ansible.cfg
  log: true
  env:
    ANSIBLE_REMOTE_TEMP: "/tmp/.ansible/tmp"
    ANSIBLE_LOCAL_TEMP: "/tmp/.ansible/local"
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_COLLECTIONS_PATHS: "../../collections"
  playbooks:
    prepare: prepare.yml
