---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Install build dependencies for psycopg2
      ansible.builtin.apt:
        name:
          - python3-pip
          - libpq-dev
          - build-essential
        state: present

    - name: Install psycopg2 with pip
      ansible.builtin.pip:
        name: psycopg2-binary
        state: present
