---
- name: Enable and restart gunicorn
  systemd:
    name: "gunicorn-{{ env_name }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true
  listen: "Enable and restart gunicorn"
